CREATE TABLE [dbo].[PRODUCTS]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [NAME] NVARCHAR(50) NOT NULL, 
    [PRICE] DECIMAL(18, 2) NOT NULL, 
    [SUBSC] BIT NOT NULL, 
    [PERIOD] INT NULL, 
    CONSTRAINT [CK_SUBSC_PERIOD_CONF_Column] CHECK (((SUBSC = 1) and PERIOD IS NOT NULL) or ((SUBSC = 0) and PERIOD IS NULL)), 
    CONSTRAINT [CK_PRODUCTS_Column] CHECK (PERIOD in (1,3,12)) 
)