CREATE TABLE [dbo].[PRODUCTS]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [NAME] NVARCHAR(50) NOT NULL, 
    [PRICE] DECIMAL(18, 2) NOT NULL, 
    [SUBSC] BIT NOT NULL, 
    [PERIOD] INT NULL, 
    CONSTRAINT [CK_SUBSC_PERIOD_CONF_Column] CHECK ([SUBSC]=(1) AND ([PERIOD]=(12) OR [PERIOD]=(3) OR [PERIOD]=(1)) OR ([SUBSC]=(0) AND [PERIOD] IS NULL))
)